version: 2

updates:
  - package-ecosystem: docker
    directory: /dockerfiles/agent
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "ubuntu"
        versions:
          - "> 24.04"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly